<?php
	$managelinksurl = '/'.$username.'/manage/';
	$requestapprovelinksurl = '/'.$username.'/manage/requestapprove/';
	$approvelistinglinksurl = '/'.$username.'/manage/approvelisting/';
	$controlapprovelinksurl = '/'.$username.'/manage/controlapprove/';
	$controlpostlinksurl = '/'.$username.'/manage/controlpost/';
	$controlpostbplinksurl = '/'.$username.'/manage/controlpostbp/';
	$logoutlinksurl = '/user/logout/';
	echo '<div class="menu_header">';
	echo '<div class="container menu-top">';
	echo '<ul class="list-inline">';
	echo '<li>';
	echo '<a href="'.base_url($managelinksurl).'">Manage</a>';
	echo '</li>';
	echo '<li>';
	echo '<a href="'.base_url($approvelistinglinksurl).'">Approve Listing(Baber Independent)</a>';
	echo '</li>';
	echo '<li>';
	echo '<a href="'.base_url($requestapprovelinksurl).'">Request Approve(Baber Independent)</a>';
	echo '</li>';
	echo '<li>';
	echo '<a href="'.base_url($controlapprovelinksurl).'">Control Approve(Baber Bussiness)</a>';
	echo '</li>';
	echo '<li>';
	echo '<a href="'.base_url($controlpostlinksurl).'">Control Posts(Baber Independent)</a>';
	echo '</li>';
	echo '<li>';
	echo '<a href="'.base_url($controlpostbplinksurl).'">Control Posts(Baber Bussiness)</a>';
	echo '</li>';
	echo '<li>';
	echo '<a href="'.base_url($logoutlinksurl).'">Log out</a>';
	echo '</li>';
	echo '</ul>';
	echo '</div>';
	echo '</div>';
?>
