<?php
$managelinksurl = '/' . $username . '/manage/';
$requestapprovelinksurl = '/' . $username . '/manage/requestapprove/';
$approvelistinglinksurl = '/' . $username . '/manage/approvelisting/';
$controlapprovelinksurl = '/' . $username . '/manage/controlapprove/';
$controllistbiposts = '/' . $username . '/manage/listbiposts/';
$controlpostbplinksurl = '/' . $username . '/manage/controlpostbp/';
$controlregisternewprofile = '/' . $username . '/manage/controlregisternewprofile/';
$controleditprofile = '/' . $username . '/manage/controleditprofile/';
$controlpostbibp = '/' . $username . '/manage/controlpost/';
$logoutlinksurl = '/user/logout/';
echo '<div class="menu_header">';
echo '<div class="container menu-top">';
echo '<ul class="list-inline">';
echo '<li>';
echo '<a href="' . base_url($managelinksurl) . '">Manage</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($controlregisternewprofile) . '">Register New Profile</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($controleditprofile) . '">Edit Profile</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($approvelistinglinksurl) . '">Approve Listing( for Baber Independent)</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($requestapprovelinksurl) . '">Request Approve( for Baber Independent)</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($controlapprovelinksurl) . '">Control Approve(for Baber Bussiness)</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($controlpostbibp) . '">Control Posts( on Bussiness Profile)</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($controllistbiposts) . '">Control Posts( for Independent Profile)</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($controlpostbplinksurl) . '">Control Posts(Baber Bussiness)</a>';
echo '</li>';
echo '<li>';
echo '<a href="' . base_url($logoutlinksurl) . '">Log out</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
?>
